# Generated by Django 5.1.2 on 2024-10-22 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_t',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
