# Generated by Django 5.0.2 on 2024-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_allowed_users_projects_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
