# Generated by Django 5.0.2 on 2024-10-22 12:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_github_userprofile_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='programming_languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('go', 'Go'), ('php', 'PHP')], max_length=45, null=True),
        ),
    ]
