# Generated by Django 5.0.2 on 2024-10-24 13:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='programming_languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('go', 'Go'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('typescript', 'TypeScript'), ('scala', 'Scala'), ('rust', 'Rust'), ('dart', 'Dart'), ('objective_c', 'Objective-C'), ('perl', 'Perl'), ('haskell', 'Haskell'), ('lua', 'Lua'), ('r', 'R'), ('matlab', 'MATLAB'), ('groovy', 'Groovy'), ('vhdl', 'VHDL'), ('verilog', 'Verilog'), ('elixir', 'Elixir'), ('clojure', 'Clojure'), ('coffeescript', 'CoffeeScript'), ('fsharp', 'F#'), ('scheme', 'Scheme'), ('julia', 'Julia'), ('nim', 'Nim'), ('smalltalk', 'Smalltalk'), ('ada', 'Ada'), ('cobol', 'COBOL'), ('fortran', 'Fortran'), ('prolog', 'Prolog'), ('racket', 'Racket'), ('ocaml', 'OCaml'), ('tcl', 'Tcl'), ('assembly', 'Assembly'), ('bash', 'Bash'), ('powershell', 'PowerShell'), ('vba', 'VBA'), ('solidity', 'Solidity'), ('apl', 'APL'), ('awk', 'Awk'), ('d', 'D'), ('erlang', 'Erlang'), ('forth', 'Forth'), ('icon', 'Icon'), ('c', 'C'), ('sql', 'SQL'), ('visual_basic', 'Visual Basic'), ('delphi', 'Delphi/Object Pascal'), ('scratch', 'Scratch')], max_length=347, null=True),
        ),
    ]
