# Generated by Django 5.1.1 on 2024-09-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
